### ISSUE TITLE
'Global' options

### ISSUE THREAD

**Issue by codermaverick** [2amigos/yii2-highcharts-widget#3]
Hi,

It seems like 'Global' options are not supported, or I'm not smart enough to figure out how to set them.

For example, to set the timezone, as per Highcharts documentations:
$(function () {
    Highcharts.setOptions({
        global: {
            timezoneOffset: 5 \* 60
        }
    });
...
http://api.highcharts.com/highcharts#global

sample: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/global/timezoneoffset/

**Comment by tonydspaniard** [comment]
bump
